cc_library(
    name = "minituna_v1",
    deps = [
        "@com_google/absl//absl/strings",
        "@com_google/absl//absl/container",
        "@com_google/absl//absl/random",
        "@com_google/absl//absl/types",
    ],
    srcs = ["minituna.cpp"],
    hdrs = ["minituna.hpp"],
)
