name: BazeliskBuild

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: |
          output
        key: minitunacpp-ci
        restore_keys: |
          minitunacpp-ci

    - name: Build
      run: |
        bazelisk --output_base output build //...

    - name: Run
      run: |
        ./bazel-bin/v1_example --n_trials=10
